name: build docker
on:
  push:
    tags:
      - 'v*'
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/fireflow:latest,${{ secrets.DOCKER_USERNAME }}/fireflow:${{ github.ref_name }}
              platforms: linux/amd64,linux/arm64
              file: ./Dockerfile
              cache-from: type=gha
              cache-to: type=gha,mode=max